version: 2

sources:
  - name: raw
    schema: raw
    tables:
      - name: trades
      - name: wazuh_alerts
      - name: benchmark_prices

  - name: lakehouse
    schema: main
    tables:
      - name: trades
        meta:
          external_location: "iceberg_scan('s3://cle-portfolio-etl/iceberg/trades/metadata/current.metadata.json')"
      - name: wazuh_alerts
        meta:
          external_location: "iceberg_scan('s3://cle-portfolio-etl/iceberg/wazuh_alerts/metadata/current.metadata.json')"
      - name: benchmark_prices
        meta:
          external_location: "iceberg_scan('s3://cle-portfolio-etl/iceberg/benchmark_prices/metadata/current.metadata.json')"
